apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-manifest-sops
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:mmUfc61LgtSSGzB8diLsTGqIoZFIFdxRWg==,iv:kz9Y2nKKAG+XR7hNoy5gZZoAajVtPqCVpmq3zdwgxSo=,tag:a9ctR25dn/xb7marYPnV+w==,type:str]
          labels:
            app: ENC[AES256_GCM,data:w7u8E5sMyLsyQXf/V9zcWvI=,iv:r4tUNlhkQOJqoQL/bWGCSxyJlYmLjigxREg/r4IKVzc=,tag:9xcU2Atjp8+oacoO8AyY6w==,type:str]
          stringData:
            POSTGRES_USER: ENC[AES256_GCM,data:k1aJssxFpljL5TA9Z3HaQg==,iv:VYe8+ol65m9VDAv/Tqoca6lF/+fmBd1rilgsFgJ7lxI=,tag:c7PX6D11q425SFCZ5H3RTQ==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:pd+s3stpqWJoAn8B1vvZ/Q==,iv:tutTMsUlCZbVzqGAyT1jkQllRi9oIxBXaYC4Y+VjmUA=,tag:o4ww787HRDFt9PZla20D0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNTFZZkJjaWhXNnFiNGRa
            WGdJYXpIaDY4eWlVajQ1T3d5ckJzamZrSVFFCkZmaVcyS1lZdkNmZXVzRlVGY3I3
            V2EyZlhqWmZSVzV0Rk93ZUZObXk3ZzgKLS0tIHFLVDNSRldMMk5SQVpJeXV2V3dC
            WEJLS1lwbTY2dkV0M1RxUWJYcUY0QWMKlUJAI1T+getqp9VmuBY6UToxvlXxObiv
            YFscCg7ax7OsEdLzFjzfuZ/tCZwSIp4xV2LcxqgC0BdTU1EXjDY4pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T09:12:57Z"
    mac: ENC[AES256_GCM,data:3IERAm8+ca6UZWqD5lZsuqQj4Q++iuSx/Bvkx/X9cT8SgoFINSPlZ41NRfUJPgI4qs4GYyyStZX06f6TwsWXsL94ce0USVirTDQXRuYm9mTZ8LTDKEAadP44OMDGBLmWqCl3Is+pQ67J68HX1TkGnLDFzOc3YS6CnIK9eGnceDA=,iv:yrriuO0OiCtLfN2znN5LVrIrAgQo+5sbmk8jGnj+CMU=,tag:qu0guHqYmxmdAQsVEuWHmA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.0
